<?php

return [
    'conservazione_title' => 'Conservazione',
    'rarita_title'        => 'Rarità',
    'metallo_title'       => 'Metallo e Patina',
    'stile_title'         => 'Stile',
    'coniazione_title'    => 'Coniazione',
    'provenienza_title'   => 'Provenienza',

    'panel_conservazione' => '<b>Lo stato di conservazione delle monete</b><br/><br/><p>Un aspetto importante nella determinazione del valore di ogni singola moneta è la corretta ed oggettiva attribuzione dello suo stato di conservazione.</p><br/><p>Per questo motivo, studiamo le tecniche di produzione ed analizziamo con la massima cura ogni esemplare, anche con l\'ausilio di potenti lenti e, qualora necessario, anche con un microscopio.</p><br/><p>La scala da noi utilizzata è quella riconosciuta in tutta Europa, che va da D (Discreto) fino a FDC (Fior di Conio).</p><br/><p>Di seguito la scala utilizzata con una breve descrizione dei vari stati di conservazione.</p><br/><div style="padding:15px"><b>D - Discreto</b><br/><p>La moneta è quasi completamente liscia: i suoi rilievi si intuiscono appena oppure forti segni ne deturpano la superficie.</p></div><div style="padding:15px"><b>B - Bello</b><br/><p>La moneta è liscia e poco leggibile.</p></div><div style="padding:15px"><b>MB - Molto Bello</b><br/><p>La moneta è molto usurata e, se i rilievi originariamente erano poco rilevati, alcune parti dell\'esemplare possono non essere leggibili.</p></div><div style="padding:15px"><b>BB - Bellissimo</b><br/><p>La moneta in questo caso ha circolato e ha evidenti tracce d\'usura, che ne hanno già intaccato il bordo, il rilievo ed il disegno. Può avere colpi sul bordo, ma non deturpanti.</p></div><div style="padding:15px"><b>SPL - Splendido</b><br/><p>Si tratta di una moneta che ha circolato pochissimo e presenta leggere tracce di circolazione. Tutti i rilievi sono ancora nitidi, ma può avere piccoli colpetti sul bordo dovuti al contatto con altre monete.</p></div><div style="padding:15px"><b>FDC - Fior di Conio</b><br/><p>È da considerarsi il più alto grado di conservazione. La moneta in questo caso non presenta alcun segno di circolazione e conserva la sua brillantezza originale, anche se è possibile ritrovare su di essa un esiguo numero di piccoli segni dovuti al contatto con le altre monete durante le fasi della produzione.</p></div><br/><p>Il Fondo Specchio (FS o Proof) non è da considerarsi uno stato di conservazione in senso stretto, ma uno speciale processo produttivo.</p><br/><p>Nell\'istogramma riportato nella scheda dell\'esemplare viene riportato graficamente il livello dello stato di conservazione. È stata scelta una scala in settantesimi per facilitare i collezionisti asiatici e americani che generalmente utilizzano la Scala Sheldon.</p><br/>',
    'panel_rarita' => '<b>La rarità</b><br/><br/><p>Altro elemento importante ai fini della determinazione del valore di una moneta è la rarità. Le monete sono prodotte sin dall\'antichità in moltissimi esemplari e, in quanto "prodotti industriali", sono spesso oggetti comuni. Ma non è sempre così.</p><br/><p>A volte ci sono esemplari veramente difficili da trovare; in alcuni casi la rarità è subordinata alla grande domanda dei collezionisti per determinate monete simboliche (ad esempio le monete di Giulio Cesare). Sull\'istogramma ne è riportato graficamente in percentuale il grado di rarità.</p><br/><p>Si passa da una percentuale molto bassa per monete comunissime (C) fino al 100% per monete della massima rarità (RRRRR).</p><br/><p><b>C</b> Comune o comunissimo · <b>NC</b> Non comune · <b>R</b> Raro · <b>RR</b> Molto raro · <b>RRR</b> Rarissimo · <b>RRRR</b> Estremamente raro · <b>RRRRR</b> Unico o soltanto alcuni esemplari noti.</p><br/>',
    'panel_metallo' => '<b>Il metallo e la patina</b><br/><br/><p>Anche la qualità e l\'aspetto del metallo di un esemplare sono un fattore molto importante nella valutazione. Ogni moneta, nel corso della sua esistenza, può avere subito i danni del tempo alla lega con cui è realizzata. Tali difetti potrebbero esistere sin dalla produzione se il metallo non era di qualità, o essere causati da una non corretta pulizia o restauro.</p><br/><p>Altro aspetto esaminato è la patina, quando presente. Col trascorrere del tempo sulle monete può formarsi una sorta di velatura. Una patina "da vecchia collezione" può rendere più gradevole un esemplare e aumentarne il pregio. Le vere patine antiche non possono che aumentare l\'attenzione dei collezionisti. Sottolineiamo "vera" in quanto è tutt\'altro che raro trovarsi di fronte a patine o colorazioni artificiali.</p><br/><p>Quando sono presenti colorazioni o moderne ossidazioni create artificialmente queste deprimono il parametro. Al contrario si potrà arrivare ad una alta percentuale per monete integre con metallo esente da particolari problemi.</p><br/>',
    'panel_stile' => '<b>Lo stile</b><br/><br/><p>Per le monete antiche un elemento fondamentale, spesso più importante della stessa conservazione, è la qualità estetica dei conii con cui sono state realizzate.</p><br/><p>Monete con uno stile grossolano, poco curato avranno una valutazione bassa sull\'istogramma. Mentre monete con uno stile più fine e ricercato avranno una valutazione superiore, fino ad arrivare al massimo grado per le produzioni numismatiche più artistiche.</p><br/>',
    'panel_coniazione' => '<b>La coniazione</b><br/><br/><p>Nel valutare una moneta è molto importante, soprattutto per le più antiche e per quelle coniate a martello, esaminare la qualità del processo produttivo e dei materiali usati per la coniazione.</p><br/><p>Esemplari con largo tondello esente da fratture, dove la coniazione è centrata sia al dritto che al rovescio, riceveranno un\'alta valutazione. Monete con forte battuta tale da produrre alti rilievi riceveranno una quotazione elevata sull\'istogramma.</p><br/><p>Al contrario, esemplari con battuta insufficiente o scivolature di conio otterranno una valutazione più bassa. Uguale importanza è riservata alla produzione con conii non usurati e non arrugginiti.</p><br/>',
    'panel_provenienza' => '<b>La provenienza</b><br/><br/><p>Altro elemento di grande importanza per la valutazione complessiva di una moneta antica è la provenienza o pedigree, ovvero la certificazione dei vari passaggi della stessa nel mercato numismatico o la passata presenza nelle varie collezioni.</p><br/><p>Una moneta con un pedigree datato, passata in aste prestigiose (Santamaria, Leu, Frank Sternberg) o che ha fatto parte di collezioni di grande importanza (A. Moretti, A. Magnaguti, S. Pozzi) avrà una percentuale più elevata su questo istogramma rispetto ad una con tracciatura soltanto recente o meno pregiata.</p><br/><p>Ogni moneta proposta dalla Moruzzi Numismatica ha una provenienza assolutamente legale e riportata nei registri delle autorità competenti.</p><br/>',
];
