<?php

return [
    'conservazione_title' => 'Grading',
    'rarita_title'        => 'Rarity',
    'metallo_title'       => 'Metal and Patina',
    'stile_title'         => 'Style',
    'coniazione_title'    => 'Coinage',
    'provenienza_title'   => 'Provenance',

    'panel_conservazione' => '<b>The grading of the coins</b><br/><br/><p>One important aspect that determines the value of a coin is the correct grading of it. For this reason we study the techniques of production, carefully analyzing each exemplar by powerful lenses and microscope if necessary.</p><br/><p>We use the European system of grading for our coins, ranging from VG (Very Good) to BU (Brilliant Uncirculated).</p><br/><p>Shown below is the system adopted with a brief description for each grade.</p><br/><p><b>VG</b> Very Good · <b>F</b> Fine · <b>VF</b> Very Fine · <b>EF</b> Extremely Fine · <b>BU</b> Brilliant Uncirculated.</p><br/><p>Proof isn\'t properly a grade but a special method of production. In the histogram present in the data sheet of each exemplar is graphically reported the level of the grade. It\'s adopted a grading in seventieths to help the Asian and American collectors accustomed to the Sheldon Grading System.</p><br/>',
    'panel_rarita' => '<b>The rarity</b><br/><br/><p>Another notable aspect in determining the value of a coin is the rarity. Coins have been produced in great quantity since ancient times and, being "industrial products", they\'re often common objects. But in many cases, this isn\'t true.</p><br/><p>There are exemplars very difficult to find; in some cases, the rarity is subordinated to the big demand of collectors for certain symbolical issues (e.g. the coins of Julius Caesar). In the histogram, the level of rarity of the item is graphically reported in percentage, from a low percentage for very common coins (C) to 100% for extremely rare ones (RRRRR).</p><br/><p><b>C</b> Common · <b>NC</b> Not common · <b>R</b> Rare · <b>RR</b> Very rare · <b>RRR</b> Particularly rare · <b>RRRR</b> Extremely rare · <b>RRRRR</b> Of the greatest rarity.</p><br/>',
    'panel_metallo' => '<b>The metal and the patina</b><br/><br/><p>Also the quality and the visual aspect of a coin\'s metal is a key factor in rating it. The metal of a coin can be damaged by the time goes on. Sometimes the defects can be caused by the low quality metal used during the minting process, or by an improper cleaning or a bad restoration.</p><br/><p>Another aspect examined in this parameter is the patina, if present. With time, a thin layer can appear on the surface of a coin. An old collection patina can increase the charm of a coin and its value. The original old patinas attract the collectors. We remark the adjective original because in many cases the patinas are artificial. Artificial patinas or modern oxidations will result in a lower rating. Aggressive polishing can damage the metal of a coin causing a low rating.</p><br/>',
    'panel_stile' => '<b>The style</b><br/><br/><p>For the ancient coins, the style of the coin dies used for the minting is really important.</p><br/><p>Coins with a coarse style will receive a low rating in the histogram. Otherwise, coins with a fine style will receive a higher evaluation up to the maximum for the most artistic ones.</p><br/>',
    'panel_coniazione' => '<b>The coinage</b><br/><br/><p>In the evaluation of the coins, especially the hammered ancient ones, it is very important to examine deeply the process of production and the materials used.</p><br/><p>Exemplars minted in a large, not fractured flan and well centered will receive a high rating. Coins with high reliefs will receive a high evaluation reported in the histogram.</p><br/><p>On the contrary, exemplars with damaged flan, not centered and with low reliefs will receive a lower rating. The same importance is reserved for the production with not worn out or not rusted coin dies.</p><br/>',
    'panel_provenienza' => '<b>The provenance</b><br/><br/><p>Another significant element to take in consideration when determining the value of a coin is the provenance or pedigree, that is the certification of the various passages of the coin in the numismatic market and collections.</p><br/><p>A coin with an old provenance, sold in prestigious auctions (Santamaria, Leu, Frank Sternberg et al.) or displayed in important collections (A. Moretti, A. Magnaguti, S. Pozzi etc.), will receive a higher percentage in the histogram than another one with a more recent or less prestigious pedigree.</p><br/><p>All the coins offered by Moruzzi Numismatica have an absolutely legal provenance registered in the Italian authorities\' lists.</p><br/>',
];
