<?php

return [
    'conservazione_title' => 'Conservation',
    'rarita_title'        => 'Rareté',
    'metallo_title'       => 'Métal et patine',
    'stile_title'         => 'Style',
    'coniazione_title'    => 'Frappe',
    'provenienza_title'   => 'Provenance',

    'panel_conservazione' => '<b>L\'état de conservation des pièces</b><br/><br/><p>Un aspect important dans la détermination de la valeur de chaque monnaie est l\'attribution correcte et objective de son état de conservation. Nous étudions les techniques de production et analysons chaque spécimen avec le plus grand soin, à l\'aide de puissantes lentilles et, si nécessaire, d\'un microscope.</p><br/><p>L\'échelle que nous utilisons est celle reconnue dans toute l\'Europe, allant de D (Discret) à FDC (Fleur de coin).</p><br/><p>D – Discret · B – Beau · MB – Très beau · BB – Très très beau · SPL – Superbe · FDC – Fleur de coin.</p><br/><p>Le Fondo Specchio (FS ou Proof) est un processus de production spécial. Dans l\'histogramme est représenté graphiquement le niveau de l\'état de conservation. Une échelle en soixante-dixièmes a été choisie pour faciliter les collectionneurs qui utilisent l\'Échelle Sheldon.</p><br/>',
    'panel_rarita' => '<b>La rareté</b><br/><br/><p>Un autre élément important dans la détermination de la valeur d\'une monnaie est la rareté. Les pièces ont été produites depuis l\'antiquité dans de nombreux exemplaires et sont souvent des objets communs. Mais ce n\'est pas toujours pareil.</p><br/><p>Parfois, il y a des exemplaires vraiment difficiles à trouver; dans certains cas, la rareté est subordonnée à la grande demande des collectionneurs pour certaines pièces symboliques. Le degré de rareté est représenté graphiquement en pourcentage sur l\'histogramme, de C à RRRRR.</p><br/><p><b>C</b> Commun · <b>NC</b> Pas commun · <b>R</b> Rare · <b>RR</b> Très rare · <b>RRR</b> Très très rare · <b>RRRR</b> Extrêmement rare · <b>RRRRR</b> Unique ou quelques exemples connus.</p><br/>',
    'panel_metallo' => '<b>Le métal et la patine</b><br/><br/><p>La qualité et l\'apparence du métal d\'un modèle sont également un facteur très important dans l\'évaluation. Chaque monnaie peut avoir subi les dommages du temps. Ces dégâts peuvent être causés par un métal de mauvaise qualité ou par un nettoyage ou une restauration incorrects.</p><br/><p>Un autre aspect examiné est la patine, lorsqu\'elle est présente. Une patine d\'ancienne collection peut rendre un exemplaire plus agréable et augmenter sa valeur. Les vraies patines anciennes attirent l\'attention des collectionneurs. Les patines artificielles dépriment le paramètre.</p><br/>',
    'panel_stile' => '<b>Le style</b><br/><br/><p>Pour les monnaies anciennes, un élément fondamental est la qualité esthétique des cônes avec lesquels elles ont été fabriquées.</p><br/><p>Les pièces avec un style grossier auront une note faible sur l\'histogramme. Les pièces avec un style plus raffiné auront une note plus élevée, jusqu\'au plus haut degré pour les productions les plus artistiques.</p><br/>',
    'panel_coniazione' => '<b>La frappe</b><br/><br/><p>Dans l\'évaluation d\'une monnaie, il est très important d\'examiner la qualité du processus de production et les matériaux utilisés pour la frappe, surtout pour les plus anciennes et celles frappées à marteau.</p><br/><p>Les exemplaires avec un grand flan sans fractures, où la frappe est centrée au droit et au revers, recevront une évaluation élevée. Les pièces avec une forte frappe produisant des hauts-reliefs recevront une note élevée sur l\'histogramme.</p><br/><p>À l\'inverse, les exemplaires avec une frappe insuffisante ou des glissements de frappe obtiendront une note inférieure. Une importance égale est réservée à la production avec des cônes non usés et non rouillés.</p><br/>',
    'panel_provenienza' => '<b>La provenance</b><br/><br/><p>Un autre élément de grande importance pour l\'évaluation globale d\'une monnaie ancienne est la provenance ou le pedigree, ou la certification des différents passages de la même dans le marché numismatique ou les collections.</p><br/><p>Une monnaie avec un pedigree daté, passée dans des ventes aux enchères prestigieuses (Santamaria, Leu, Frank Sternberg) ou qui a fait partie de collections de grande importance (A. Moretti, A. Magnaguti, S. Pozzi) aura un pourcentage plus élevé sur l\'histogramme.</p><br/><p>Chaque pièce proposée par Moruzzi Numismatica a une origine absolument légale et est enregistrée dans les registres des autorités compétentes.</p><br/>',
];
