<?php

/**
 * Mappa sezioni e articoli della Guida al collezionismo.
 *
 * Ogni articolo espone:
 * - route: named route Laravel (guide.*)
 * - section: chiave sezione in sections
 * - slug: segmento URL italiano (default); slug per tutte le lingue in config/guide_article_slugs.php
 * - legacy: file .html root del sito moruzzi.it (redirect 301)
 * - phase: priorità migrazione contenuti (1 = subito)
 * - redirect_route: se impostato, la route guida reindirizza a route esistente
 * - nav: mostra in sidebar / menu (default true)
 */
return [
    'prefix' => [
        'it' => 'guida',
        'en' => 'guide',
        'fr' => 'guide',
        'de' => 'leitfaden',
        'es' => 'guia',
    ],

    'sections' => [
        'overview' => [
            'slug' => [
                'it' => '',
                'en' => '',
                'fr' => '',
                'de' => '',
                'es' => '',
            ],
        ],
        'collector' => [
            'slug' => [
                'it' => 'per-il-collezionista',
                'en' => 'for-collectors',
                'fr' => 'pour-le-collectionneur',
                'de' => 'fuer-sammler',
                'es' => 'para-coleccionistas',
            ],
        ],
        'ancient_rome' => [
            'slug' => [
                'it' => 'monete-antiche-romane',
                'en' => 'ancient-roman-coins',
                'fr' => 'monnaies-antiques-romaines',
                'de' => 'antike-roemische-muenzen',
                'es' => 'monedas-antiguas-romanas',
            ],
        ],
        'italian_collections' => [
            'slug' => [
                'it' => 'collezioni-italiane',
                'en' => 'italian-collections',
                'fr' => 'collections-italiennes',
                'de' => 'italienische-sammlungen',
                'es' => 'colecciones-italianas',
            ],
        ],
        'international' => [
            'slug' => [
                'it' => 'monete-internazionali',
                'en' => 'international-coins',
                'fr' => 'monnaies-internationales',
                'de' => 'internationale-muenzen',
                'es' => 'monedas-internacionales',
            ],
        ],
        'medals_banknotes' => [
            'slug' => [
                'it' => 'banconote-e-medaglie',
                'en' => 'banknotes-and-medals',
                'fr' => 'billets-et-medailles',
                'de' => 'banknoten-und-medailen',
                'es' => 'billetes-y-medallas',
            ],
        ],
    ],

    'articles' => [
        // --- Hub / panoramica (phase 1) ---
        [
            'id' => 'index',
            'route' => 'guide.index',
            'section' => 'overview',
            'slug' => '',
            'legacy' => [],
            'phase' => 1,
            'nav' => false,
        ],
        [
            'id' => 'intro_numismatica',
            'route' => 'guide.intro_numismatica',
            'section' => 'overview',
            'slug' => 'la-numismatica-e-il-collezionismo',
            'legacy' => ['la_numismatica_ed_il_collezionismo.html'],
            'phase' => 1,
        ],
        [
            'id' => 'investment',
            'route' => 'guide.investment',
            'section' => 'overview',
            'slug' => 'numismatica-e-investimento',
            'legacy' => ['numismatica_e_investimento.html'],
            'phase' => 1,
        ],
        [
            'id' => 'bibliography',
            'route' => 'guide.bibliography',
            'section' => 'overview',
            'slug' => 'bibliografia-numismatica',
            'legacy' => ['la_bibliografia_numismatica.html'],
            'phase' => 1,
        ],
        [
            'id' => 'faq',
            'route' => 'guide.faq',
            'section' => 'overview',
            'slug' => 'faq',
            'legacy' => [
                'faq_domande_frequenti.html',
                'faq_-_frequent_asked_questions.html',
                'faq_-_questions_frequents.html',
                'faq_-preguntas_mas_frecuentes.html',
                'faq_haufig_gestellte_fragen.html',
                'faq---questoes-frequentes.html',
            ],
            'phase' => 1,
        ],

        // --- Per il collezionista ---
        [
            'id' => 'abbreviations',
            'route' => 'guide.abbreviations',
            'section' => 'collector',
            'slug' => 'abbreviazioni-monete',
            'legacy' => ['le_abbreviazioni_per_le_monete.html', 'le_abbreviazioni_testo.html'],
            'redirect_route' => 'shop.abbreviations',
            'phase' => 1,
        ],
        [
            'id' => 'collecting_ancient',
            'route' => 'guide.collecting_ancient',
            'section' => 'collector',
            'slug' => 'collezionare-monete-antiche',
            'legacy' => ['collezionare_monete_antiche_in_italia.html'],
            'redirect_route' => 'shop.collecting',
            'phase' => 1,
        ],
        [
            'id' => 'conservation',
            'route' => 'guide.conservation',
            'section' => 'collector',
            'slug' => 'stato-di-conservazione',
            'legacy' => ['monete_stato_di_conservazione.html'],
            'phase' => 1,
        ],
        [
            'id' => 'rarity',
            'route' => 'guide.rarity',
            'section' => 'collector',
            'slug' => 'la-rarita',
            'legacy' => ['la_rarita.html'],
            'phase' => 1,
        ],
        [
            'id' => 'fakes',
            'route' => 'guide.fakes',
            'section' => 'collector',
            'slug' => 'i-falsi',
            'legacy' => ['i_falsi.html'],
            'phase' => 1,
        ],
        [
            'id' => 'cork_coins',
            'route' => 'guide.cork_coins',
            'section' => 'collector',
            'slug' => 'monete-suberate',
            'legacy' => ['le_monete_suberate.html'],
            'phase' => 2,
        ],
        [
            'id' => 'watches',
            'route' => 'guide.watches',
            'section' => 'collector',
            'slug' => 'orologi-da-collezione',
            'legacy' => ['gli_orologi_da_collezione.html', 'orologi_da_collezione.html'],
            'phase' => 2,
        ],

        // --- Monete antiche romane ---
        [
            'id' => 'rome_in_coins',
            'route' => 'guide.rome_in_coins',
            'section' => 'ancient_rome',
            'slug' => 'roma-nelle-monete',
            'legacy' => ['roma_nelle_monete.html'],
            'phase' => 1,
        ],
        [
            'id' => 'aes_rude_signatum',
            'route' => 'guide.aes_rude_signatum',
            'section' => 'ancient_rome',
            'slug' => 'dall-aes-rude-all-aes-signatum',
            'legacy' => ['dall_aes_rude_all_aes_signatum.html'],
            'phase' => 2,
        ],
        [
            'id' => 'republican_rome',
            'route' => 'guide.republican_rome',
            'section' => 'ancient_rome',
            'slug' => 'monete-di-roma-repubblicana',
            'legacy' => ['le_monete_di_roma_repubblicana.html'],
            'phase' => 2,
        ],
        [
            'id' => 'imperial_titles',
            'route' => 'guide.imperial_titles',
            'section' => 'ancient_rome',
            'slug' => 'titolatura-imperiale',
            'legacy' => ['la_titolatura_imperiale.html'],
            'phase' => 2,
        ],
        [
            'id' => 'roman_women_augustae',
            'route' => 'guide.roman_women_augustae',
            'section' => 'ancient_rome',
            'slug' => 'donna-romana-ritratti-auguste',
            'legacy' => [
                'la_donna_romana_e_i_ritratti_di_auguste.html',
                'la_donna_romana_nei_ritratti_delle_auguste.html',
            ],
            'phase' => 2,
        ],
        [
            'id' => 'spintriae',
            'route' => 'guide.spintriae',
            'section' => 'ancient_rome',
            'slug' => 'spintrie-e-tessere',
            'legacy' => [
                'spintrie_e_tessere_romane_con_numerali.html',
                'spintrie_e_tessere_con_numerali.html',
            ],
            'phase' => 2,
        ],
        [
            'id' => 'ara_pacis',
            'route' => 'guide.ara_pacis',
            'section' => 'ancient_rome',
            'slug' => 'ara-pacis',
            'legacy' => ['l_ara_pacis.html'],
            'phase' => 2,
        ],
        [
            'id' => 'temple_janus',
            'route' => 'guide.temple_janus',
            'section' => 'ancient_rome',
            'slug' => 'tempio-di-giano',
            'legacy' => ['il_tempio_di_giano.html'],
            'phase' => 2,
        ],
        [
            'id' => 'domitianus',
            'route' => 'guide.domitianus',
            'section' => 'ancient_rome',
            'slug' => 'domitianus',
            'legacy' => ['domitianus.html'],
            'phase' => 2,
        ],
        [
            'id' => 'giovino_solidus',
            'route' => 'guide.giovino_solidus',
            'section' => 'ancient_rome',
            'slug' => 'solido-di-giovino',
            'legacy' => ['un_solido_di_giovino.html'],
            'phase' => 2,
        ],

        // --- Collezioni italiane ---
        [
            'id' => 'veii',
            'route' => 'guide.veii',
            'section' => 'italian_collections',
            'slug' => 'vittorio-emanuele-ii',
            'legacy' => ['vittorio_emanuele_ii.html'],
            'phase' => 2,
        ],
        [
            'id' => 'umberto_i',
            'route' => 'guide.umberto_i',
            'section' => 'italian_collections',
            'slug' => 'umberto-i',
            'legacy' => ['umberto_i.html'],
            'phase' => 2,
        ],
        [
            'id' => 'veiii',
            'route' => 'guide.veiii',
            'section' => 'italian_collections',
            'slug' => 'vittorio-emanuele-iii',
            'legacy' => ['vittorio_emanuele_iii.html'],
            'phase' => 2,
        ],
        [
            'id' => 'rsi',
            'route' => 'guide.rsi',
            'section' => 'italian_collections',
            'slug' => 'repubblica-sociale-italiana',
            'legacy' => ['repubblica_sociale_italiana.html'],
            'phase' => 2,
        ],
        [
            'id' => 'luogotenenza',
            'route' => 'guide.luogotenenza',
            'section' => 'italian_collections',
            'slug' => 'luogotenenza',
            'legacy' => ['luogotenenza.html'],
            'phase' => 2,
        ],
        [
            'id' => 'repubblica_italiana',
            'route' => 'guide.repubblica_italiana',
            'section' => 'italian_collections',
            'slug' => 'repubblica-italiana',
            'legacy' => ['repubblica_italiana.html'],
            'phase' => 2,
        ],

        // --- Monete internazionali ---
        [
            'id' => 'international_overview',
            'route' => 'guide.international_overview',
            'section' => 'international',
            'slug' => 'panoramica',
            'legacy' => ['le_monete_internazionali.html'],
            'phase' => 2,
        ],
        [
            'id' => 'tetradrachm_athens',
            'route' => 'guide.tetradrachm_athens',
            'section' => 'international',
            'slug' => 'tetradramma-di-atene',
            'legacy' => ['il_tetradramma_di_atene.html'],
            'phase' => 2,
        ],
        [
            'id' => 'stater_corinth',
            'route' => 'guide.stater_corinth',
            'section' => 'international',
            'slug' => 'statere-di-corinto',
            'legacy' => ['lo_statere_di_corinto.html'],
            'phase' => 2,
        ],
        [
            'id' => 'tetradrachm_alexander',
            'route' => 'guide.tetradrachm_alexander',
            'section' => 'international',
            'slug' => 'tetradramma-di-alessandro-magno',
            'legacy' => ['il_tetradramma_di_alessandro_magno.html'],
            'phase' => 2,
        ],
        [
            'id' => 'denarius_republican',
            'route' => 'guide.denarius_republican',
            'section' => 'international',
            'slug' => 'denario-romano-repubblicano',
            'legacy' => [
                'il_denario_romano_di_epoca_repubblicana.html',
                'il_denario_romano_repubblicano.html',
            ],
            'phase' => 2,
        ],
        [
            'id' => 'denarius_imperial',
            'route' => 'guide.denarius_imperial',
            'section' => 'international',
            'slug' => 'denario-romano-imperiale',
            'legacy' => [
                'il_denario_romano_di_epoca_imperiale.html',
                'il_denario_romano_di_epoca_repubblicana.html',
            ],
            'phase' => 2,
        ],
        [
            'id' => 'aureus',
            'route' => 'guide.aureus',
            'section' => 'international',
            'slug' => 'aureo-romano',
            'legacy' => ['l_aureo_romano.html', 'monete-d-oro.html', 'monete_d_oro.html'],
            'phase' => 2,
        ],
        [
            'id' => 'byzantine_solidus',
            'route' => 'guide.byzantine_solidus',
            'section' => 'international',
            'slug' => 'solido-bizantino',
            'legacy' => ['il_solido_bizantino.html'],
            'phase' => 2,
        ],
        [
            'id' => 'florin',
            'route' => 'guide.florin',
            'section' => 'international',
            'slug' => 'fiorino',
            'legacy' => ['il_fiorino.html', 'the_florin.html', 'der_florin.html', 'le_florin.html', 'el_florin.html'],
            'phase' => 2,
        ],
        [
            'id' => 'ducat',
            'route' => 'guide.ducat',
            'section' => 'international',
            'slug' => 'ducato',
            'legacy' => ['il_ducato.html'],
            'phase' => 2,
        ],
        [
            'id' => 'taler',
            'route' => 'guide.taler',
            'section' => 'international',
            'slug' => 'tallero',
            'legacy' => ['il_tallero.html'],
            'phase' => 2,
        ],
        [
            'id' => 'leeuwenndaalder',
            'route' => 'guide.leeuwenndaalder',
            'section' => 'international',
            'slug' => 'leeuwenndaalder',
            'legacy' => ['leeuwenndaalder.html', 'il_leeuwenndaalder.html'],
            'phase' => 2,
        ],
        [
            'id' => 'spanish_8_escudos',
            'route' => 'guide.spanish_8_escudos',
            'section' => 'international',
            'slug' => 'moneta-spagnola-8-escudos',
            'legacy' => ['la_moneta_spagnola_da_8_escudos.html'],
            'phase' => 2,
        ],
        [
            'id' => 'spanish_8_reales',
            'route' => 'guide.spanish_8_reales',
            'section' => 'international',
            'slug' => 'moneta-spagnola-8-reales',
            'legacy' => ['la_moneta_spagnola_da_8_reales.html'],
            'phase' => 2,
        ],
        [
            'id' => 'dollar',
            'route' => 'guide.dollar',
            'section' => 'international',
            'slug' => 'dollaro',
            'legacy' => ['il_dollaro.html'],
            'phase' => 2,
        ],
        [
            'id' => 'marengo',
            'route' => 'guide.marengo',
            'section' => 'international',
            'slug' => 'marengo',
            'legacy' => ['il_marengo.html'],
            'phase' => 2,
        ],
        [
            'id' => 'five_franc_scudo',
            'route' => 'guide.five_franc_scudo',
            'section' => 'international',
            'slug' => 'scudo-da-5-franchi',
            'legacy' => ['lo_scudo_da_5_franchi.html'],
            'phase' => 2,
        ],
        [
            'id' => 'pound_sterling',
            'route' => 'guide.pound_sterling',
            'section' => 'international',
            'slug' => 'sterlina-inglese',
            'legacy' => ['la_sterlina_inglese.html'],
            'phase' => 2,
        ],
        [
            'id' => 'euro',
            'route' => 'guide.euro',
            'section' => 'international',
            'slug' => 'euro',
            'legacy' => ['l_euro.html', 'euro.html'],
            'phase' => 2,
        ],

        // --- Banconote e medaglie ---
        [
            'id' => 'birth_of_medal',
            'route' => 'guide.birth_of_medal',
            'section' => 'medals_banknotes',
            'slug' => 'nascita-della-medaglia',
            'legacy' => ['la_nascita_della_medaglia.html'],
            'phase' => 2,
        ],
        [
            'id' => 'banknote_history',
            'route' => 'guide.banknote_history',
            'section' => 'medals_banknotes',
            'slug' => 'storia-della-banconota',
            'legacy' => ['una_breve_storia_della_banconota.html'],
            'phase' => 2,
        ],
        [
            'id' => 'banca_romana',
            'route' => 'guide.banca_romana',
            'section' => 'medals_banknotes',
            'slug' => 'banca-romana-regno-italia',
            'legacy' => ['la_banca_romana_durante_il_regno_d_italia.html'],
            'phase' => 2,
        ],
        [
            'id' => 'banknote_abbreviations',
            'route' => 'guide.banknote_abbreviations',
            'section' => 'medals_banknotes',
            'slug' => 'abbreviazioni-banconote',
            'legacy' => ['le_abbreviazioni_per_le_banconote.html'],
            'phase' => 2,
        ],
        [
            'id' => 'banknote_conservation',
            'route' => 'guide.banknote_conservation',
            'section' => 'medals_banknotes',
            'slug' => 'banconote-stato-di-conservazione',
            'legacy' => ['banconote_stato_di_conservazione.html'],
            'phase' => 2,
        ],
        [
            'id' => 'paper_money_europe',
            'route' => 'guide.paper_money_europe',
            'section' => 'medals_banknotes',
            'slug' => 'cartamoneta-europa',
            'legacy' => [
                'la_cartamoneta_d_europa.html',
                'banconote_e_cartamoneta_d_europa.html',
            ],
            'phase' => 3,
        ],
        [
            'id' => 'paper_money_overseas',
            'route' => 'guide.paper_money_overseas',
            'section' => 'medals_banknotes',
            'slug' => 'cartamoneta-oltremare',
            'legacy' => ['banconote_e_cartamoneta_d_oltremare.html'],
            'phase' => 3,
        ],
        [
            'id' => 'medals_collection_2006',
            'route' => 'guide.medals_collection_2006',
            'section' => 'medals_banknotes',
            'slug' => 'collezione-medaglie-2006',
            'legacy' => ['una_collezione_di_medaglie_2006.html'],
            'phase' => 3,
        ],
    ],
];
