<?php

return [
    'conservazione_title' => 'Erhaltungszustand',
    'rarita_title'        => 'Seltenheit',
    'metallo_title'       => 'Metall und Patina',
    'stile_title'         => 'Stil',
    'coniazione_title'    => 'Prägung',
    'provenienza_title'   => 'Herkunft',

    'panel_conservazione' => '<b>Der Erhaltungszustand von Münzen</b><br/><br/><p>Ein wichtiger Aspekt bei der Bestimmung des Wertes einer Münze ist die korrekte Zuordnung des Erhaltungszustands. Aus diesem Grund analysieren wir jedes Exemplar mit größter Sorgfalt, auch mit Hilfe leistungsstarker Linsen und gegebenenfalls eines Mikroskops.</p><br/><p>Die von uns verwendete Skala ist die in ganz Europa anerkannte, die von D (Discret) bis BU (Brilliant Uncirculated) reicht.</p><br/><p>D – Discret · B – Gut · MB – Sehr gut · BB – Schön · SPL – Vorzüglich · BU – Stempelglanz.</p><br/><p>Spiegelglanz (FS oder Proof) ist ein spezielles Produktionsverfahren. Im Histogramm wird der Erhaltungsgrad grafisch dargestellt. Es wurde eine Skala in Siebzigstel gewählt, um Sammlern zu helfen, die die Sheldon-Skala verwenden.</p><br/>',
    'panel_rarita' => '<b>Die Seltenheit</b><br/><br/><p>Ein weiteres bemerkenswertes Element zur Bestimmung des Wertes einer Münze ist die Seltenheit. Münzen wurden seit der Antike in großen Mengen produziert und sind oft gewöhnliche Gegenstände. Aber in vielen Fällen ist dies nicht wahr.</p><br/><p>Es gibt Exemplare, die sehr schwer zu finden sind; in einigen Fällen ist die Seltenheit der großen Nachfrage der Sammler nach bestimmten symbolischen Münzen untergeordnet. Im Histogramm wird der Seltenheitsgrad in Prozent angegeben, von C bis RRRRR.</p><br/><p><b>C</b> Häufig · <b>NC</b> Nicht häufig · <b>R</b> Selten · <b>RR</b> Sehr selten · <b>RRR</b> Besonders selten · <b>RRRR</b> Äußerst selten · <b>RRRRR</b> Von größter Seltenheit.</p><br/>',
    'panel_metallo' => '<b>Das Metall und die Patina</b><br/><br/><p>Auch die Qualität und das Erscheinungsbild des Metalls einer Münze sind ein wichtiger Faktor bei der Bewertung. Das Metall einer Münze kann im Laufe der Zeit beschädigt werden. Die Mängel können durch minderwertiges Metall oder unsachgemäße Reinigung verursacht werden.</p><br/><p>Ein weiterer Aspekt ist die Patina, falls vorhanden. Eine alte Sammlungspatina kann den Reiz einer Münze und ihren Wert steigern. Die originalen alten Patinas ziehen die Sammler an. Künstliche Patinas führen zu einer niedrigeren Bewertung. Aggressive Politur kann das Metall beschädigen.</p><br/>',
    'panel_stile' => '<b>Der Stil</b><br/><br/><p>Für antike Münzen ist der Stil der verwendeten Münzstempel von großer Bedeutung.</p><br/><p>Münzen mit einem groben Stil erhalten eine niedrige Bewertung im Histogramm. Münzen mit einem feinen Stil erhalten eine höhere Bewertung bis zum Maximum für die künstlerisch wertvollsten.</p><br/>',
    'panel_coniazione' => '<b>Die Prägung</b><br/><br/><p>Bei der Bewertung von Münzen, insbesondere der gehämmerten antiken Münzen, ist es sehr wichtig, den Herstellungsprozess und die verwendeten Materialien genau zu untersuchen.</p><br/><p>Exemplare, die auf einem großen, nicht gebrochenen Schrötling geprägt und gut zentriert sind, erhalten eine hohe Bewertung. Münzen mit hohem Relief erhalten eine hohe Bewertung im Histogramm.</p><br/><p>Exemplare mit beschädigtem Schrötling oder niedrigem Relief erhalten eine niedrigere Bewertung. Die gleiche Bedeutung wird der Produktion mit nicht abgenutzten oder nicht verrosteten Münzstempeln beigemessen.</p><br/>',
    'panel_provenienza' => '<b>Die Herkunft</b><br/><br/><p>Ein weiteres bedeutendes Element bei der Bestimmung des Wertes einer Münze ist die Herkunft oder der Stammbaum, also die Zertifizierung der verschiedenen Stationen der Münze im numismatischen Markt und in Sammlungen.</p><br/><p>Eine Münze mit einer alten Herkunft, die in prestigeträchtigen Auktionen (Santamaria, Leu, Frank Sternberg usw.) verkauft wurde oder in wichtigen Sammlungen ausgestellt ist, erhält einen höheren Prozentsatz im Histogramm.</p><br/><p>Alle von Moruzzi Numismatica angebotenen Münzen haben eine absolut legale Herkunft, die in den Listen der italienischen Behörden registriert ist.</p><br/>',
];
