<?php

return [
    'conservazione_title' => 'Conservación',
    'rarita_title'        => 'Rareza',
    'metallo_title'       => 'Metal y pátina',
    'stile_title'         => 'Estilo',
    'coniazione_title'    => 'Acuñación',
    'provenienza_title'   => 'Procedencia',

    'panel_conservazione' => '<b>El estado de conservación de las monedas</b><br/><br/><p>Un aspecto importante en la determinación del valor de cada moneda es la correcta y objetiva atribución del estado de conservación. Por esta razón, estudiamos las técnicas de producción y analizamos cada ejemplar con el máximo cuidado, también con la ayuda de potentes lentes y, si es necesario, con un microscopio.</p><br/><p>La escala que utilizamos es la reconocida en toda Europa, que va desde D (Discreto) hasta FDC (Flor de Cuño).</p><br/><p>D – Discreto · B – Bueno · MB – Muy Bueno · BB – Bellísimo · SPL – Excelente · FDC – Flor de Cuño.</p><br/><p>El Fondo Espejo (FS o Proof) es un proceso de producción especial. En el histograma se representa gráficamente el nivel del estado de conservación. Se ha elegido una escala en setentaavos para facilitar a los coleccionistas que utilizan la escala Sheldon.</p><br/>',
    'panel_rarita' => '<b>La rareza</b><br/><br/><p>Otro aspecto notable para determinar el valor de una moneda es la rareza. Las monedas se han producido en grandes cantidades desde tiempos antiguos y a menudo son objetos comunes. Pero en muchos casos, esto no es cierto.</p><br/><p>Existen ejemplares muy difíciles de encontrar; en algunos casos, la rareza está subordinada a la gran demanda de los coleccionistas por ciertas emisiones simbólicas. En el histograma, el nivel de rareza del objeto se informa gráficamente en porcentaje, desde C hasta RRRRR.</p><br/><p><b>C</b> Común · <b>NC</b> No común · <b>R</b> Rara · <b>RR</b> Muy rara · <b>RRR</b> Particularmente rara · <b>RRRR</b> Extremadamente rara · <b>RRRRR</b> De la mayor rareza.</p><br/>',
    'panel_metallo' => '<b>El metal y la pátina</b><br/><br/><p>La calidad y el aspecto visual del metal de una moneda también son factores clave para su evaluación. El metal de una moneda puede dañarse con el paso del tiempo. Los defectos pueden ser causados por metal de baja calidad o por una limpieza incorrecta o una mala restauración.</p><br/><p>Otro aspecto examinado en este parámetro es la pátina, si está presente. Una pátina de antigua colección puede aumentar el encanto de una moneda y su valor. Las pátinas antiguas originales atraen a los coleccionistas. Las pátinas artificiales resultarán en una calificación más baja.</p><br/>',
    'panel_stile' => '<b>El estilo</b><br/><br/><p>Para las monedas antiguas, un elemento fundamental es la calidad estética de los troqueles con los que se han realizado.</p><br/><p>Las monedas con un estilo tosco tendrán una valoración baja en el histograma. Las monedas con un estilo más fino y elaborado tendrán una valoración superior, hasta llegar al grado máximo para las producciones numismáticas más artísticas.</p><br/>',
    'panel_coniazione' => '<b>La acuñación</b><br/><br/><p>En la evaluación de las monedas, especialmente las antiguas acuñadas a martillo, es muy importante examinar profundamente el proceso de producción y los materiales utilizados.</p><br/><p>Los ejemplares acuñados en un flan grande, no fracturado y bien centrado recibirán una alta calificación. Las monedas con altos relieves recibirán una alta evaluación informada en el histograma.</p><br/><p>Por el contrario, los ejemplares con flan dañado, no centrado y con bajos relieves recibirán una calificación más baja. La misma importancia se reserva para la producción con troqueles no desgastados o no oxidados.</p><br/>',
    'panel_provenienza' => '<b>La procedencia</b><br/><br/><p>Otro elemento significativo a tener en cuenta al determinar el valor de una moneda es la procedencia o pedigree, es decir, la certificación de los diversos pasos de la moneda en el mercado numismático y las colecciones.</p><br/><p>Una moneda con una procedencia antigua, vendida en subastas prestigiosas (Santamaria, Leu, Frank Sternberg, etc.) o expuesta en importantes colecciones (A. Moretti, A. Magnaguti, S. Pozzi, etc.), recibirá un porcentaje más alto en el histograma.</p><br/><p>Todas las monedas ofrecidas por Moruzzi Numismatica tienen una procedencia absolutamente legal registrada en las listas de las autoridades italianas.</p><br/>',
];
